<?php
/**
 * Default Sidebar
 *
 * @package      responsive_mobile
 * @license      license.txt
 * @copyright    2014 CyberChimps Inc
 * @since        0.0.1
 *
 * Please do not edit this file. This file is part of the responsive_mobile Framework and all modifications
 * should be made in a child theme.
 */

// If this file is called directly, abort.
if ( ! defined( 'WPINC' ) ) {
	die;
}

/*
 * Load the correct sidebar according to the page layout
 */
$layout = responsive_mobile_get_layout();
switch ( $layout ) {
	case 'content-sidebar-page':
		get_sidebar( 'right' );
		return;
		break;

	case 'sidebar-content-page':
		get_sidebar( 'left' );
		return;
		break;

	case 'content-sidebar-half-page':
		get_sidebar( 'right-half' );
		return;
		break;

	case 'sidebar-content-half-page':
		get_sidebar( 'left-half' );
		return;
		break;

	case 'full-width-page':
		return;
		break;

	case 'three-column-posts':
		return;
		break;
}
?>
<?php responsive_mobile_widgets_before(); ?>
<div id="widgets" class="widget-area default-sidebar" role="complementary" itemscope="itemscope" itemtype="http://schema.org/WPSideBar">
	<?php responsive_mobile_widgets(); ?>
	<?php if ( !dynamic_sidebar( 'main-sidebar' ) ) : ?>
		<?php
		/*
		* Code hi?n th? b�i vi?t li�n quan trong c�ng 1 category
		*/
		$categories = get_the_category(get_the_ID());
		$currentPostId = get_the_ID();
		if ($categories){
			echo '<aside id="sameCatalogyPost" class="widget-wrapper">';
			$category_ids = array();
			foreach($categories as $individual_category) $category_ids[] = $individual_category->term_id;
			$args=array(
				'category__in' => $category_ids,
				'posts_per_page' => 999, // So bai viet dc hien thi
				'order'   => 'ASC',
			);
			$my_query = new wp_query($args);
			if( $my_query->have_posts() ):
				echo '<h4 class="widget-title">List Post In Same Catology</h4><ul>';
				while ($my_query->have_posts()):$my_query->the_post();
					if(get_the_ID() == $currentPostId){
						?>
						<li><a href="<?php the_permalink() ?>" title="<?php the_title_attribute(); ?>"><b> <img class="item-sidebar-icon" src="<?php apply_url("/wp-content/uploads/2019/08/item.png"); ?>"> <?php the_title(); ?></b></a></li>
						<?php
					}else{
						?>
						<li><img class="item-sidebar-icon" src="<?php apply_url("/wp-content/uploads/2019/08/item.png"); ?>">   <a href="<?php the_permalink() ?>" title="<?php the_title_attribute(); ?>">   <?php the_title(); ?></a></li>
						<?php
					}
				endwhile;
				echo '</ul>';
			endif; wp_reset_query();
			echo '</aside>';
		}
		?>
		<aside id="archives" class="widget-wrapper hidden-by-quoc" >
			<h3 class="widget-title"><?php _e( 'In Archive', 'responsive-mobile' ); ?></h3>
			<ul>
				<?php wp_get_archives( array( 'type' => 'monthly' ) ); ?>
			</ul>
		</aside>

	<?php endif; // end sidebar widget area ?>
	<?php responsive_mobile_widgets_end(); ?>
</div><!-- #default-sidebar -->
<?php responsive_mobile_widgets_after(); ?>
